version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: xterm
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "thingif/build.gradle" }}
      - run:
          name: build sdk
          command: |
            ./gradlew :thingif:build
            ./gradlew :thingif:makeAAR
      - store_artifacts:
          path: thingif/build/artifacts/
          destination: sdk-aar
      - run:
          name: generate doc and archive
          command: |
            ./gradlew :thingif:generateJavadoc
            ./gradlew :thingif:javadocArchive
      - store_artifacts:
          path: thingif/build/outputs/
          destination: java-doc
      - run: ./gradlew :thingif:test
      - store_test_results:
          path: thingif/build/test-results

  large_test:
    docker:
        - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: xterm

    steps:
      - checkout
      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-25;google_apis;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-25;google_apis;armeabi-v7a"
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
          background: true
      - run:
          name: Wait emulator
          command: |
            # wait for it to have booted
            circle-android wait-for-boot
            # unlock the emulator screen
            sleep 30
            adb shell input keyevent 82
      - run:
          name: Run Tests
          command: ./gradlew :thingiftest:connectedAndroidTest
      - store_test_results:
          path: thingiftest/build/outputs/androidTest-results


workflows:
  version: 2
  build_test:
    jobs:
      - build
      - large_test