version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "thingif/build.gradle" }}
      - run:
          name: pre build
          command: |
            export TERM=xterm
            ./gradlew :thingif:build
            ./gradlew :thingif:makeAAR
      - store_artifacts:
          path: thingif/build/artifacts/
          destination: built

workflows:
  version: 2
  build_test:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/