version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: xterm
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "thingif/build.gradle" }}
      - run:
          name: build sdk
          command: |
            ./gradlew :thingif:build
            ./gradlew :thingif:makeAAR
      - store_artifacts:
          path: thingif/build/artifacts/
          destination: sdk-aar
      - run:
          name: generate doc and archive
          command: |
            ./gradlew :thingif:generateJavadoc
            ./gradlew :thingif:javadocArchive
      - save_cache:
          key: api-doc-{{ .Revision }}
          paths:
            - thingif/build/outputs
      - store_artifacts:
          path: thingif/build/outputs/
          destination: java-doc
      - run: ./gradlew :thingif:test
      - store_test_results:
          path: thingif/build/test-results
  deployment:
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: xterm
    steps:
      - checkout
      - restore_cache:
          key: api-doc-{{ .Revision }}
      - run: bash circleci_scripts/release_doc.sh
      - run: ./gradlew bintrayUpload
  large_test:
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: xterm
    steps:
      - checkout
      - run:
          name: update packages
          command: sdkmanager --update
      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-22;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-22;default;armeabi-v7a" | android update avd -n test
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
          background: true
      - run:
          name: build sdk
          command: ./gradlew :thingif:build
      - run:
          name: Run Tests
          command: ./gradlew :thingiftest:connectedAndroidTest
      - store_test_results:
          path: thingiftest/build/outputs/androidTest-results/connected/

workflows:
  version: 2
  build_test:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - large_test:
          requires:
            - build
          filters:
            tags:
              ignore: /.*/
  build_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+){0,2}((-.*)?)?$/
      - deployment:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+(\.[0-9]+){0,2}((-.*)?)?$/