version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: xterm
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "thingif/build.gradle" }}
      - run:
          name: build sdk
          command: |
            ./gradlew :thingif:build
            ./gradlew :thingif:makeAAR
      - store_artifacts:
          path: thingif/build/artifacts/
          destination: sdk-aar
      - run:
          name: generate doc and archive
          command: |
            ./gradlew :thingif:generateJavadoc
            ./gradlew :thingif:javadocArchive
      - store_artifacts:
          path: thingif/build/outputs/javadoc
      - store_artifacts:
          path: thingif/build/outputs/archive/apidoc*.zip

workflows:
  version: 2
  build_test:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/